<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="img\00.png" />
    <None Remove="img\1arrow.png" />
    <None Remove="img\1home.png" />
    <None Remove="img\1logout.png" />
    <None Remove="img\1menu.png" />
    <None Remove="img\1setting.png" />
    <None Remove="img\1user.png" />
    <None Remove="img\2home.png" />
    <None Remove="img\2logout.png" />
    <None Remove="img\2menu.png" />
    <None Remove="img\2setting.png" />
    <None Remove="img\2user.png" />
    <None Remove="img\ArowDown.png" />
    <None Remove="img\ArowDownLite.png" />
    <None Remove="img\ArowUp.png" />
    <None Remove="img\ArowUpLite.png" />
    <None Remove="img\arrow.png" />
    <None Remove="img\BackAuth.jpg" />
    <None Remove="img\BackMain.jpg" />
    <None Remove="img\CategoryBlue.png" />
    <None Remove="img\CategoryGreen.png" />
    <None Remove="img\CategoryOrange.png" />
    <None Remove="img\CategoryPurple.png" />
    <None Remove="img\CategoryRed.png" />
    <None Remove="img\CategoryWhite.png" />
    <None Remove="img\ClientsBlue.png" />
    <None Remove="img\ClientsGreen.png" />
    <None Remove="img\ClientsOrange.png" />
    <None Remove="img\ClientsPurple.png" />
    <None Remove="img\ClientsRed.png" />
    <None Remove="img\ClientsWhite.png" />
    <None Remove="img\close.png" />
    <None Remove="img\editl.png" />
    <None Remove="img\eventBlue.png" />
    <None Remove="img\eventGreen.png" />
    <None Remove="img\eventOrange.png" />
    <None Remove="img\eventPurple.png" />
    <None Remove="img\eventRed.png" />
    <None Remove="img\eventWhite.png" />
    <None Remove="img\holidays-party.png" />
    <None Remove="img\LoginUser.png" />
    <None Remove="img\LoginUserBlue.png" />
    <None Remove="img\LoginUserGreen.png" />
    <None Remove="img\LoginUserOrange.png" />
    <None Remove="img\LoginUserPurple.png" />
    <None Remove="img\LoginUserRed.png" />
    <None Remove="img\LogLock.png" />
    <None Remove="img\LogoutBlue.png" />
    <None Remove="img\LogoutGreen.png" />
    <None Remove="img\LogoutOrange.png" />
    <None Remove="img\LogoutPurple.png" />
    <None Remove="img\LogoutRed.png" />
    <None Remove="img\LogoutWhite.png" />
    <None Remove="img\mapBlue.png" />
    <None Remove="img\mapGreen.png" />
    <None Remove="img\mapOrange.png" />
    <None Remove="img\mapPurple.png" />
    <None Remove="img\mapRed.png" />
    <None Remove="img\mapWhite.png" />
    <None Remove="img\party.ico" />
    <None Remove="img\party.png" />
    <None Remove="img\plus.png" />
    <None Remove="img\RoleBlue.png" />
    <None Remove="img\RoleGreen.png" />
    <None Remove="img\RoleOrange.png" />
    <None Remove="img\RolePurple.png" />
    <None Remove="img\RoleRed.png" />
    <None Remove="img\RoleWhite.png" />
    <None Remove="img\Search.png" />
    <None Remove="img\SearchLite.png" />
    <None Remove="img\SettingBlue.png" />
    <None Remove="img\SettingGreen.png" />
    <None Remove="img\SettingOrange.png" />
    <None Remove="img\SettingPurple.png" />
    <None Remove="img\SettingRed.png" />
    <None Remove="img\SettingWhite.png" />
    <None Remove="img\trash.png" />
    <None Remove="img\up-down-arow.png" />
    <None Remove="img\up-down-arowLite.png" />
    <None Remove="img\userSettingBlue.png" />
    <None Remove="img\userSettingGreen.png" />
    <None Remove="img\userSettingOrange.png" />
    <None Remove="img\userSettingPurple.png" />
    <None Remove="img\userSettingRed.png" />
    <None Remove="img\userSettingWhite.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.SqlServer.Server" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\EventManagementSolution\EventManagement.Data\EventManagement.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="img\00.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\1arrow.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\1home.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\1logout.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\1menu.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\1setting.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\1user.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\2home.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\2logout.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\2menu.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\2setting.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\2user.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\ArowDown.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\ArowDownLite.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\ArowUp.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\ArowUpLite.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\arrow.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\BackAuth.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\BackMain.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\CategoryBlue.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\CategoryGreen.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\CategoryOrange.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\CategoryPurple.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\CategoryRed.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\CategoryWhite.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\ClientsBlue.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\ClientsGreen.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\ClientsOrange.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\ClientsPurple.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\ClientsRed.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\ClientsWhite.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\close.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\editl.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\eventBlue.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\eventGreen.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\eventOrange.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\eventPurple.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\eventRed.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\eventWhite.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\holidays-party.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\LoginUser.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\LoginUserBlue.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\LoginUserGreen.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\LoginUserOrange.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\LoginUserPurple.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\LoginUserRed.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\LogLock.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\LogoutBlue.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\LogoutGreen.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\LogoutOrange.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\LogoutPurple.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\LogoutRed.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\LogoutWhite.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\mapBlue.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\mapGreen.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\mapOrange.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\mapPurple.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\mapRed.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\mapWhite.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\party.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\party.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\plus.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\RoleBlue.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\RoleGreen.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\RoleOrange.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\RolePurple.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\RoleRed.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\RoleWhite.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\Search.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\SearchLite.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\SettingBlue.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\SettingGreen.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\SettingOrange.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\SettingPurple.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\SettingRed.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\SettingWhite.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\trash.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\up-down-arow.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\up-down-arowLite.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\userSettingBlue.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\userSettingGreen.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\userSettingOrange.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\userSettingPurple.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\userSettingRed.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="img\userSettingWhite.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\Authentication.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Page>
  </ItemGroup>

</Project>
